function getDeck() {
  return { black: black(), white: white() };
}

function black() {
  return [
    "A romantic candlelit dinner would be incomplete without __________.",
    "After Hurricane Katrina, Sean Penn brought __________ to the people of New Orleans.",
    "After the earthquake, Sean Penn brought __________ to the people of Haiti.",
    "Alternative medicine is now embracing the curative powers of __________.",
    "And I would have gotten away with it, too, if it hadn't been for __________.",
    "Anthropologists have recently discovered a primitive tribe that worships __________.",
    "BILLY MAYS HERE FOR __________.",
    "Betcha can't have just one!",
    "But before I kill you, Mr. Bond, I must show you __________.",
    "Coming to Broadway this season, __________: The Musical.",
    "Dear Abby, I'm having some trouble with __________ and would like your advice.",
    "Due to a PR fiasco, Walmart no longer offers __________.",
    "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of __________.",
    "During sex, I like to think about __________.",
    "He who controls __________ controls the world.",
    "How am I maintaining my relationship status?",
    "I do not know with what weapons World War III will be fought, but World War IV will be fought with __________.",
    "I drink to forget __________.",
    "I got 99 problems but __________ ain't one.",
    "I learned the hard way that you can't cheer up a grieving friend with __________.",
    "I wish I hadn't lost the instruction manual for __________.",
    "I'm sorry, Professor, but I couldn't complete my homework because of __________.",
    "In 1,000 years, when paper money is but a distant memory, __________ will be our currency.",
    "In L.A. County Jail, word is you can trade 200 cigarettes for __________.",
    "In Michael Jackson's final moments, he thought about __________.",
    "In Rome, there are whisperings that the Vatican has a secret room devoted to __________.",
    "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on __________.",
    "In his new self-produced album, Kanye West raps over the sounds of __________.",
    "In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated __________.",
    "In the distant future, historians will agree that __________ marked the beginning of America's decline.",
    "In the new Disney Channel Original Movie, Hannah Montana struggles with __________ for the first time. ",
    "Instead of coal, Santa now gives the bad children __________.",
    "It's a pity that kids these days are all getting involved with __________.",
    "It's a trap!",
    "Life for American Indians was forever changed when the White Man introduced them to __________.",
    "Life was difficult for cavemen before __________.",
    "MTV's new reality show features eight washed-up celebrities living with __________.",
    "Major League Baseball has banned __________ for giving players an unfair advantage.",
    "Maybe she's born with it. Maybe it's __________.",
    "Next from J.K. Rowling: Harry Potter and the Chamber of __________.",
    "Next on ESPN2: The World Series of __________.",
    "Science will never explain the origin of __________.",
    "Sorry everyone, I just __________.",
    "Studies show that lab rats navigate mazes 50% faster after being exposed to __________.",
    "TSA guidelines now prohibit __________ on airplanes.",
    "The CIA now interrogates enemy agents by repeatedly subjecting them to __________.",
    "The U.S. has begun airdropping __________ to the children of Afghanistan.",
    "The class field trip was completely ruined by __________.",
    "The socialist governments of Scandinavia have declared that access to __________ is a basic human right.",
    "This is the way the world ends / This is the way the world ends / Not with a bang but with __________.",
    "This season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only __________ and his wits. ",
    "War! What is it good for?",
    "What am I giving up for Lent?",
    "What are my parents hiding from me?",
    "What brought the orgy to a grinding halt?",
    "What did I bring back from Mexico?",
    "What did Vin Diesel eat for dinner?",
    "What did the US airdrop to the children of Afghanistan?",
    "What do old people smell like?",
    "What does Dick Cheney prefer?",
    "What don't you want to find in your Chinese food?",
    "What ended my last relationship?",
    "What gets better with age?",
    "What gives me uncontrollable gas?",
    "What has been making life difficult at the nudist colony?",
    "What helps Obama unwind?",
    "What is Batman's guilty pleasure?",
    "What never fails to liven up the party?",
    "What will I bring back in time to convince people that I am a powerful wizard?",
    "What will always get you laid?",
    "What would grandma find disturbing, yet oddly charming?",
    "What's Teach for America using to inspire inner city students to succeed?",
    "What's a girl's best friend?",
    "What's my anti-drug?",
    "What's my secret power?",
    "What's that smell?",
    "What's that sound?",
    "What's the crustiest?",
    "What's the gift that keeps on giving?",
    "What's the most emo?",
    "What's the new fad diet?",
    "What's the next Happy Meal toy?",
    "What's there a ton of in heaven?",
    "When I am President of the United States, I will create the Department of __________.",
    "When I am a billionaire, I shall erect a 50-foot statue to commemorate __________.",
    "When I pooped, what came out of my butt?",
    "When I'm in prison, I'll have __________ smuggled in.",
    "When Pharaoh remained unmoved, Moses called down a Plague of __________.",
    "When all else fails, I can always masturbate to __________.",
    "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on __________.",
    "White people like __________.",
    "Who stole the cookies from the cookie jar?",
    "Why am I sticky?",
    "Why can't I sleep at night?",
    "Why do I hurt all over?",
    "__________. Betcha can't have just one!",
    "__________. High five, bro.",
    "__________. It's a trap!",
    "__________. That's how I want to die.",
    "__________: Good to the last drop.",
    "__________: Kid-tested, mother-approved.",
    "__________: good to the last drop.",
    "__________: kid tested, mother approved.",
    "__________? There's an app for that.",
  ];
}

function white() {
  return [
"(I am doing Kegels right now.)",
"360 no scopes.",
"400 years of colonial atrocities.",
"50,000 volts straight to the nipples.",
"72 virgins.",
"8 oz. of sweet Mexican black-tar heroin.",
"A 1971 Ford Fiesta.",
"A Chealsea smile.",
"A Gypsy curse.",
"A LAN party.",
"A Super Soaker™ full of cat piss.",
"A bag of magic beans.",
"A balanced breakfast.",
"A big hoopla about nothing.",
"A bit of slap and tickle.",
"A bitch slap.",
"A bleached arsehole.",
"A blow job while driving.",
"A boat load of cocaine.",
"A brain tumor.",
"A bucket of fish heads.",
"A can of whoop-ass.",
"A cartoon camel enjoying the smooth, refreshing taste of a cigarette.",
"A clandestine butt scratch.",
"A cool-box full of organs.",
"A death ray.",
"A defective condom.",
"A disappointing birthday party.",
"A drive-by shooting.",
"A falcon with a cap on its head.",
"A fanny fart.",
"A fetus.",
"A foetus.",
"A foul mouth.",
"A gassy antelope.",
"A gentle caress of the inner thigh.",
"A giant purple dildo sword.",
"A ginger's freckled ballbag",
"A good sniff.",
"A grande sugar-free iced soy caramel macchiato.",
"A gypsy curse.",
"A homoerotic volleyball montage.",
"A hot mess.",
"A lifetime of sadness.",
"A live studio audience.",
"A look-see.",
"A mad cow.",
"A madman who lives in a police box and kidnaps women.",
"A mating display.",
"A micropenis.",
"A micropig wearing a tiny raincoat and booties.",
"A middle-aged man on roller skates.",
"A mime having a stroke.",
"A moment of silence.",
"A monkey smoking a cigar.",
"A mopey zoo lion.",
"A murder most foul.",
"A neglected Tamagotchi™.",
"A nice hot cup of tea.",
"A posh wank.",
"A pyramid of severed heads.",
"A really cool hat.",
"A robust mongoloid.",
"A sad handjob.",
"A salty surprise.",
"A sassy black woman.",
"A sausage festival.",
"A saxophone solo.",
"A sea of troubles.",
"A snapping turtle biting the tip of your penis.",
"A sober Irishman who doesn't care for potatoes.",
"A spastic nerd.",
"A stray pube.",
"A subscription to Men's Fitness.",
"A thermonuclear detonation.",
"A thousand Scottish warriors lifting their kilts in unison.",
"A time travel paradox.",
"A tiny horse.",
"A tribe of warrior women.",
"A vajazzled vagina.",
"A vindaloo poo.",
"A walrus with a beret.",
"A white van man.",
"A windmill full of corpses.",
"A zesty breakfast burrito.",
"AIDS.",
"ALL the things!",
"Margaret Thatcher.",
"Abstinence.",
"Abusive fathers.",
"Active listening.",
"Actually taking candy from a baby.",
"African children.",
"Agriculture.",
"Alcoholism.",
"All-you-can-eat Chinese buffet for £4.99.",
"Altar boys.",
"American Gladiators.",
"Amputees.",
"An 8-ball.",
"An AK-47 assault rifle.",
"An M. Night. Shyamalan plot twist.",
"An Oedipus complex.",
"An argument with Richard Dawkins.",
"An asymmetric boob job.",
"An entrenched class system.",
"An erection that lasts longer than four hours.",
"An honest cop with nothing left to lose.",
"An icepick lobotomy.",
"An icy handjob from a skanky hooker.",
"An oversized lollipop.",
"An ugly face.",
"An uppercut.",
"Anal beads.",
"Another goddamn vampire movie.",
"Anything that comes out of Prince Philip's mouth.",
"Arnold Schwarzenegger.",
"Asians who aren't good at math.",
"Assless chaps.",
"Attitude.",
"Auschwitz.",
"Authentic Mexican cuisine.",
"Autocannibalism.",
"BATMAN!!!",
"Badger culling.",
"Balls.",
"Banana Hammocks.",
"Bananas in Pajamas.",
"Barack Obama.",
"Barney's rape dungeon.",
"Battlefield amputations.",
"Beer Pong.",
"Bees?",
"Being a dick to children.",
"Being a motherfucking sorcerer.",
"Being fabulous.",
"Being fat and stupid.",
"Being marginalised.",
"Being on fire.",
"Being rich.",
"Bestiality.",
"Bill Gates pissing on Steve Jobs's grave.",
"Bill Nye the Science Guy.",
"Bingeing and purging.",
"Bitches.",
"Black people.",
"Bling.",
"Blood, toil, tears, and sweat.",
"Blowing up parliament.",
"Blowing your hand off with a firework.",
"Bogies.",
"Bong hits for Jesus.",
"Booby-trapping the house to foil burglars.",
"Borat's one piece.",
"Breaking out into song and dance.",
"Britney Spears at 55.",
"Brown people.",
"Buckfast Tonic Wine.",
"Cards Against Humanity.",
"Catapults.",
"Catdog.",
"Centaurs.",
"Chainsaws for hands.",
"Cheating in the Paralympics.",
"Cheating in the Special Olympics.",
"Cheeky bum sex.",
"Child abuse.",
"Child beauty pageants.",
"Children on leashes.",
"Chivalry.",
"Christopher Walken.",
"Chunks of dead prostitute.",
"Civilian casualties.",
"Classist undertones.",
"Coat hanger abortions.",
"Cockfights.",
"College.",
"Concealing an erection.",
"Consensual sex.",
"Consultants.",
"Cookie Monster devouring the Eucharist wafers.",
"Copping a feel.",
"Cottaging.",
"Count Chocula.",
"Cranky Kong.",
"Crippling debt.",
"Crucifixion.",
"Crumpets with the Queen.",
"Crystal meth.",
"Cuddling.",
"Cybernetic enhancements.",
"Daddies® Brown Sauce.",
"Daddy issues.",
"Darth Vader.",
"Date rape.",
"Dave Matthews Band.",
"David Bowie flying in on a tiger made of lightning.",
"David Cameron.",
"Dead babies.",
"Dead parents.",
"Demi Moore's bush.",
"Dental dams.",
"Destroying the evidence.",
"Dick Cheney.",
"Dick fingers.",
"Dirty hippies.",
"Dirty nappies.",
"Dogging.",
"Doin' it in the butt.",
"Doing a shit in Pudsey Bear's eyehole.",
"Doing the right thing.",
"Donald Trump.",
"Donkey Shows.",
"Douchebags on their iPhones.",
"Drinking alone.",
"Dropping a chandelier on your enemies and riding the rope up.",
"Druids.",
"Drum circles.",
"Dry humping.",
"Duke Nukem Forever.",
"Dwarf tossing.",
"Dying of dysentery.",
"Dying.",
"Eastern European Turbo-Folk music.",
"Eating 120 Macdonalds burgers®.",
"Eating all of the cookies before the AIDS bake-sale.",
"Eating the last known bison.",
"Ecstasy.",
"Ed Balls.",
"Edible knickers.",
"Edible underpants.",
"Elderly Japanese men.",
"Elderly Japanese men.",
"Embryonic stem cells.",
"Emma Watson.",
"Emotions.",
"England.",
"Erectile dysfunction.",
"Establishing dominance.",
"Ethnic cleansing.",
"Eugenics.",
"Exactly what you'd expect.",
"Excalibur.",
"Exchanging pleasantries.",
"Expecting a burp and vomiting on the floor.",
"Explosions.",
"Extremely tight trousers.",
"Faffing about.",
"Faith healing.",
"Famine.",
"Fancy Feast®.",
"Farting and walking away.",
"Fear itself.",
"Feeding Rosie O'Donnell.",
"Fiery poops.",
"Figgy pudding.",
"Finger painting.",
"Fingering.",
"Firing a rifle into the air while balls deep into a squealing hog.",
"Five litres of Special Brew.",
"Flash flooding.",
"Flavouredred condoms.",
"Flesh-eating bacteria.",
"Flightless birds.",
"Flying sex snakes.",
"Foreskin.",
"Forgetting the Alamo.",
"Former President George W. Bush.",
"Free samples.",
"Friction.",
"Friendly fire.",
"Friends who eat all the snacks.",
"Friends with benefits.",
"Frolicking.",
"Finger monkeys.",
"Frubes®.",
"Fruit Fuckers.",
"Full frontal nudity.",
"Funky fresh rhymes.",
"Gandhi.",
"Garth Brooks.",
"Gary Glitter.",
"Geese.",
"Genghis Khan.",
"Genital piercings.",
"Genital warts.",
"Gentleman's Relish.",
"German dungeon porn.",
"Germans on holiday.",
"Getting drunk on mouthwash.",
"Getting high on bath salts.",
"Getting naked and watching CBeebies.",
"Getting really high.",
"Getting wed, having a few kids, taking some pictures, retiring to the south of France, and dying.",
"Ghosts.",
"Giving 110%.",
"Global warming.",
"Gloryholes.",
"Goats eating coins.",
"Goblins.",
"God.",
"Golden showers.",
"Grandma.",
"Grave robbing.",
"Growing a pair.",
"Guys who don't call.",
"Haggis.",
"Half-arsed foreplay.",
"Harry Potter erotica.",
"Heart-warming orphans.",
"Heath Ledger.",
"Her Majesty, Queen Elizabeth II.",
"Her Royal Highness, Queen Elizabeth II.",
"Heteronormativity.",
"Hipsters on their iPhones at Starbucks.",
"Hitler's moustache.",
"Homeless people.",
"Homo milk.",
"Hoola-Hoops.",
"Hooters.",
"Hope.",
"Hordes of zombies.",
"Hormone injections.",
"Horrifying laser hair removal accidents.",
"Horse meat.",
"Hospice care.",
"Hot cheese.",
"Hot people.",
"Hulk Hogan.",
"Hump Day.",
"Hungry Hungry Hippos.",
"Hunting accidents.",
"Hurling one's body down a hill in pursuit of a wheel of cheese.",
"Hurricane Katrina.",
"Impotence.",
"Inappropriate yelling.",
"Inappropriate yodelling.",
"Incest.",
"Indiana Jones.",
"Insane Clown Posse.",
"Intelligent design.",
"Italians.",
"Jade Goody's cancerous remains.",
"Jedward.",
"Jehova's Witnesses.",
"Jeremy Clarkson being harried by a quarrel of sparrows.",
"Jeremy Clarkson catching his scrotum on a curtain hook.",
"Jerking off into a pool of children's tears.",
"Jimmy Savile.",
"John Wilkes Booth.",
"Judge Judy.",
"Just touching David Beckham's hair.",
"Justin Bieber.",
"Kamikaze pilots.",
"Kanye West.",
"Kappa.",
"Keanu Reeves.",
"Keeping Christ in Christmas.",
"Kids with bum cancer.",
"Kim Jong-il.",
"KitKats®.",
"LYNX® Body Spray.",
"Lactation.",
"Lady Gaga.",
"Lance Armstrong's missing testicle.",
"Land mines.",
"Laying an egg.",
"Leaked footage of Kate Middleton's endoscopy.",
"Leaving an awkward voicemail.",
"Leprosy.",
"Letting yourself go.",
"Licking things to claim them as your own.",
"Lockjaw.",
"Loose lips.",
"Lumberjack fantasies.",
"Lunchables™.",
"Made-for-TV movies.",
"Madeleine McCann.",
"Making a pouty face.",
"Making sex at her.",
"Man meat.",
"Mario Kart.",
"Mario brutally murdering Sonic.",
"Marky Mark and the Funky Bunch.",
"Master Chef.",
"Masturbation.",
"Mathletes.",
"Mating season.",
"Maureen of Blackpool, Reader's Wife of the Year 1988.",
"Me time.",
"MechaHitler.",
"Men.",
"Menstruation.",
"Menstural rage.",
"Michael Jackson.",
"Michelle Obama's arms.",
"Millwall fans.",
"Mining accidents.",
"Monkeys throwing shit.",
"Morgan Freeman's voice.",
"Mouth herpes.",
"Mr. Fancy Pants.",
"Mr. Hankey the Christmas Poo.",
"Mr. Snuffleupagus.",
"Muhammad (Praise Be Unto Him).",
"Multiple stab wounds.",
"Mutually-assured destruction.",
"Muzzy.",
"My collection of high-tech sex toys.",
"My ex-wife.",
"My genitals.",
"My humps.",
"My inner demons.",
"My relationship status.",
"My sex life.",
"My soul.",
"My vagina.",
"Naked News.",
"Natalie Portman.",
"Natural male enhancement.",
"Natural selection.",
"Nazis.",
"Necrophilia.",
"Nessie.",
"New Age music.",
"Nickelback.",
"Nicolas Cage.",
"Nipple blades.",
"Nipple pads.",
"Nocturnal emissions.",
"Not giving a shit about the Third World.",
"Not reciprocating oral sex.",
"Not wearing trousers.",
"Nu Metal.",
"Nurse Joy.",
"Obesity.",
"Object permanence.",
"Oestrogen.",
"Old-people smell.",
"One Direction's supple, hairless bodies.",
"One trillion quid.",
"Oompa-Loompas.",
"OpalFruits.",
"Opposable thumbs.",
"Outsourcing jobs to India.",
"Overcompensation.",
"Oversized lollipops.",
"PCP.",
"Pac-man uncontrollably guzzling cum.",
"Paedophiles.",
"Panda sex.",
"Parting the Red Sea.",
"Party poopers.",
"Passable transvestites.",
"Passing a kidney stone.",
"Passive-aggressive Post-It™ notes.",
"Passive-agression.",
"Paedophiles.",
"Peeing a little bit.",
"Penis envy.",
"Penn and Teller.",
"Perfunctory foreplay.",
"Picking up girls at the abortion clinic.",
"Pictures of boobs.",
"Pixelated bukkake.",
"Police brutality.",
"Pooping back and forth. Forever.",
"Poor life choices.",
"Poor people.",
"Poorly written Star Wars® fan fiction.",
"Poorly-timed Holocaust jokes.",
"Pop Tarts®.",
"Porn stars.",
"Powerful thighs.",
"Prancing.",
"Praying the gay away.",
"Pre-teens.",
"Pretending to care.",
"Pronouncing the names of northern Welsh towns.",
"Pterodactyl eggs.",
"Puberty.",
"Public ridicule.",
"Pulling out.",
"Puppies!",
"Pussy Galore.",
"Queefing.",
"Queen Elizabeth's immaculate anus.",
"Racially-biased exam questions.",
"Racism.",
"Rainbows and magic.",
"Raping and pillaging.",
"Raptor attacks.",
"Re-gifting.",
"Rehab.",
"Repression.",
"Republicans.",
"Rich, chocolatey Ovaltine®.",
"Riding off into the sunset.",
"Ring Pops™.",
"Ringworm.",
"Ripping off the Beatles.",
"Robert Downey, Jr.",
"RoboCop.",
"Rohypnol.",
"Ronald Reagan.",
"Roofies.",
"Rubbing Boris Johnson's belly until he falls asleep.",
"Same-sex ice dancing.",
"Sarah Palin.",
"Saxophone solos.",
"Scalping the Milkybar Kid.",
"Scalping.",
"Science.",
"Scientology.",
"Scotsman marring their sheep.",
"Scousers.",
"Scrubbing under the folds.",
"Sean Connery.",
"Sean Penn.",
"Seduction.",
"Self-loathing.",
"Sex in your mouth.",
"Sexting.",
"Sexual tension.",
"Sexy pillow fights.",
"Shag carpeting.",
"Shapeshifters.",
"Shaquille O'Neal's acting career.",
"Sharing needles.",
"Sheepskin Condoms.",
"Shiny objects.",
"Shipping convicts to Australia.",
"Shitting out a perfect Cumberland sausage.",
"Silence.",
"Skeletor.",
"Slapping a biscuit out of an orphan's mouth.",
"Smallpox blankets.",
"Smegma.",
"Smooth jazz.",
"Sniffing glue.",
"Snotsicles.",
"Sobbing into a Birds-Eye® frozen Dinner.",
"Soiling oneself.",
"Some bloody peace and quiet.",
"Song of Storms.",
"Sonic brutally murdering Mario.",
"Soup that is too hot.",
"Soviet Russia.",
"Spaniards.",
"Spanish soap operas.",
"Spectacular abs.",
"Speedrunning life.",
"Sperm whales.",
"Sperm.",
"Sponge baths.",
"Spontaneous Combustion.",
"Spontaneous human combustion.",
"Stalin.",
"Stephen Hawking talking dirty.",
"Stifling a giggle at the mention of Hutus and Tutsis.",
"Stormtroopers.",
"Stranger danger.",
"Strong female characters.",
"Stunt doubles.",
"Substitute teachers.",
"Sunshine and rainbows.",
"Surprise sex!",
"Swag.",
"Sweet, sweet vengeance.",
"Swooping.",
"Synergistic.",
"Syrupy sex with a maple tree.",
"Take-backsies.",
"Taking off your shirt.",
"Tangled Slinkys.",
"Teaching a robot to love.",
"Team-building exercises.",
"Teenage pregnancy.",
"Tennent's Super Strong Lager.",
"Tentacle porn.",
"Terabytes of donkey porn.",
"Testicular torsion.",
"That one gay Teletubby.",
"That thing that electrocutes your abs.",
"The American Dream.",
"The BNP.",
"The Bible.",
"The Big Bang.",
"The Black Death.",
"The Blood of Christ.",
"The Chinese gymnastics team.",
"The Columbine Shooting.",
"The Dance of the Sugar Plum Fairy.",
"The Devil himself.",
"The Eiffel Tower.",
"The Famous Five.",
"The Force.",
"The French.",
"The Great Depression.",
"The Hamburglar.",
"The Hillsborough Disaster.",
"The Hokey Pokey.",
"The Holy Bible.",
"The Honey Monster.",
"The Hustle.",
"The Jews.",
"The KKK.",
"The Make-A-Wish® Foundation.",
"The Mushroom Kingdom.",
"The North.",
"The Oculus Rift.",
"The Pope.",
"The Power Rangers.",
"The Rapture.",
"The Rev. Dr. Martin Luther King, Jr.",
"The Royal Canadian Mounted Police.",
"The Scouts.",
"The South.",
"The Stig.",
"The Tempur-Pedic® Swedish Sleep System™.",
"The Thong Song.",
"The Three-Fifths compromise.",
"The Trail of Tears.",
"The Underground.",
"The World of Warcraft.",
"The art of seduction.",
"The bloody Welsh.",
"The brown note.",
"The clitoris.",
"The deformed.",
"The end of days.",
"The entire cast of Downton Abbey.",
"The female orgasm.",
"The final circle of Hell.",
"The folly of man.",
"The forbidden fruit.",
"The gays.",
"The glass ceiling.",
"The hardworking Mexican.",
"The heart of a child.",
"The hero of time.",
"The homosexual agenda.",
"The inevitable heat death of the universe.",
"The invisible hand.",
"The light of a billion suns.",
"The milk man.",
"The miracle of childbirth.",
"The petty troubles of the landed gentry.",
"The placenta.",
"The profoundly handicapped.",
"The shitty remains of Pizza Hut®.",
"The sudden appearance of the Go Compare man.",
"The taint; the grundle; the fleshy fun-bridge.",
"The terrorists.",
"The token minority.",
"The true meaning of Christmas.",
"The truffle shuffle.",
"The unstoppable tide of Islam.",
"The violation of our most basic human rights.",
"The way James Bond treats women.",
"The world's tallest midget.",
"The Übermensch.",
"Third base.",
"This answer is postmodern.",
"Those times when you get sand in your vagina.",
"Throwing a virgin into a volcano.",
"Tickle Me Elmo.",
"Tiger Woods.",
"Tits.",
"Tom Cruise.",
"Too much hair gel.",
"Tories.",
"Trench foot.",
"Tweeting.",
"Two midgets shitting into a bucket.",
"Two midgets stacked up pretending to be one person.",
"Unfathomable stupidity.",
"Uppercuts.",
"Used knickers.",
"Using hot sauce as lube.",
"Vehicular manslaughter.",
"Viagra®.",
"Vigilante justice.",
"Vigorous jazz hands.",
"Viking Metal.",
"Vikings.",
"Waffles.",
"Waiting 'til marriage.",
"Waking up half-naked in a Little Chef car park.",
"Walt Disney's frozen head.",
"Wanking into a pool of children's tears.",
"Waterboarding.",
"Wearing underwear inside-out to avoid doing laundry.",
"Wet dreams.",
"When you fart and a little bit comes out.",
"Whipping it out.",
"White people.",
"White privilege.",
"Wifely duties.",
"Will Smith.",
"William Shatner.",
"Winking at old people.",
"Wiping her bum.",
"Women in yoghurt adverts.",
"Women's suffrage.",
"World peace.",
"Yeast."
  ];
}

exports.getDeck = getDeck;
